name: Build Folia

on:
  workflow_dispatch:
    inputs:
      createrelease:
        description: '创建发行版'
        required: true
        default: 'false'
        type: boolean
      release_name:
        description: '发行版名称'
        required: false
        default: 'Folia-Latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: 'PaperMC/Folia'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: another-repo
      - name: Get Commit ID from the other repository
        id: folia
        run: |
          cd another-repo
          COMMIT_ID=$(git rev-parse HEAD)
          echo "commit_id=$COMMIT_ID" >> $GITHUB_OUTPUT
          echo "Commit ID: $COMMIT_ID"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Build Folia .jar'
        run: |
          sh build.sh
      - uses: actions/upload-artifact@v4
        if: ${{inputs.createrelease == 'false' || inputs.createrelease == false}}
        with:
          name: FoliaToGo
          path: Folia/build/libs/*.jar
      - uses: actions/create-release@v1.1.4
        if: ${{inputs.createrelease == 'true' || inputs.createrelease == true}}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('folia-latest-{}', steps.folia.outputs.commit_id) }}
          release_name: ${{inputs.release_name}}
          body: This is latest folia build number ${{steps.folia.outputs.commit_id}}!
          draft: false
          prerelease: false
      - if: ${{inputs.createrelease == 'true' || inputs.createrelease == true}}
        name: Upload Assets to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_ID=${{ steps.create_release.outputs.id }}
          UPLOAD_FOLDER="Folia/build/libs"
          EXT_FILTER="*.jar"
          find "$UPLOAD_FOLDER" -type f -name "$EXT_FILTER" | while read -r FILE; do
            echo "Uploading file: $FILE"
            gh release upload ${{ format('folia-latest-{}', steps.folia.outputs.commit_id) }} "$FILE" --clobber
          done
        #uses: actions/upload-release-asset@v1
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
          #upload_url: ${{steps.create_release.outputs.upload_url}}
          #asset_path: Folia/build/libs/*
          #asset_name: Folia-build.jar
          #asset_content_type: application/zip
