name: Build Folia

on:
  workflow_dispatch:
    inputs:
      createrelease:
        description: '创建发行版'
        required: true
        default: false
        type: boolean
      release_name:
        description: '发行版名称'
        required: false
        default: 'Folia-Latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Build Folia .jar'
        run: |
          sh build.sh
      - uses: actions/upload-artifact@v4
        if: ${{inputs.createrelease == 'false'}}
        with:
          name: FoliaToGo
          path: Folia/build/libs/*.jar
      - uses: actions/create-release@v1.1.4
        if: ${{inputs.createrelease == 'true'}}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: folia-latest
          release_name: ${{inputs.release_name}}
          body: This is latest folia build from the day this created!
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        if: ${{inputs.createrelease == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: Folia/build/libs/*.jar
          asset_name: Folia-build.jar
          asset_content_type: application/zip
